times= ('Internacional', 'São Paulo', 'Vasco', 'Fluminense', 'Atlético-MG', 'Palmeiras', 'Fortaleza', 'Bahia', 'Flamengo', 'Santos', 'Ceará', 'Grêmio', 'Athletico-PR', 'Coritiba', 'Botafogo', 'Corinthians', 'Bragantino', 'Goiás', 'Sport','Atlético-GO')
print ('-=' * 20)
print(f'A tabela do brasileirão é {times}')
print ('-=' * 20)
print(f'Os 5 primeiros times da tabela são {times[0:6]}')
print ('-=' * 20)
print(f'Os 4 últimos da tabela são {times[16:]}')
print ('-=' * 20)
print('Os times em ordem alfabética são ',end = ' ')
print(sorted(times))
print ('-=' * 20)
print(f'O São Paulo está na {times.index("São Paulo")+1}ª posição.')
